### ISSUE TITLE
add/verify support for schema import

### ISSUE THREAD

**Issue by pbcornell** [amzn/ion-schema-kotlin#1]
SchemaImpl.kt includes some logic to support this.  At a minimum, tests are needed in the (likely) event that imports are not implemented fully/correctly.

**Comment by dgkimamzn** [comment]
The current implementation of the import has a mismatch with the schema. As seen [here](https://github.com/amzn/ion-schema-kotlin/blob/master/src/software/amazon/ionschema/internal/SchemaImpl.kt#L51), the id of the import is being interpreted as a symbol, but the spec defines it as a string.

[Where spec defines as string](https://amzn.github.io/ion-schema/docs/spec.html#schema-authorities)
[Example that should work](https://amzn.github.io/ion-schema/docs/spec.html#customer-profile-data)

**Comment by pbcornell** [comment]
Thanks @dgkimamzn.  Yes that's a bug, schema id should be a string as indicated by the spec.  You're welcome to submit a pull request to fix that if you'd like.

**Comment by pbcornell** [comment]
Bug described above (import schema id incorrectly being interpreted as a symbol) has been fixed in #41.
