### ISSUE TITLE
add support for the document type

### ISSUE THREAD

**Issue by pbcornell** [amzn/ion-schema-kotlin#11]
This deserves some careful API design.

**Comment by pbcornell** [comment]
> Is document more like iterable or more like iterable?

Please clarify, thanks.

> The specification seems to indicate that document isA any but doesn't declare as much what X is for document hasMany X.

If you're looking for some upper-bound for X, there isn't a hard limit as far as the spec is concerned, although it could be constrained on a user-defined type (e.g., by an `occurs` constraint on an element within an `ordered_elements` constraint).

**Comment by xcaliber2001ad** [comment]
Also, IDL processing an ionValue as shown in checkValue method using ION.singleValue in README.md) vs checking if a document is valid feel like two very big different operations.  The specifications might do good in calling out some abstract methods an IDL engine might do:

(a) check if an Ion value matches a schema, returning true/false
(b) check if an Ion stream / document matches a schema, returning true/false
(c) check if an Ion value matches a schema, returning an empty/non-empty list of validation misses
(d) check if an Ion document matches a schema, returning an empty/non-empty list of validation misses
(e) more?

Dependency-wise it _feels_ like (b) is a superset of (a), (d) of (c), (c) of (a), and (d) of (b) [thus also (d) over (a) transitively].  Contextually knowing whether you're consuming one stream as a single value / document vs. checking each value in the Ion stream one-at-a-time feels a little weird for the client to have to tell you, but maybe that's unavoidable.

**Comment by pbcornell** [comment]
> Is document more like iterable[ionValue] or more like iterable[any]?

*Aha, much clearer, thanks!  Isn't markdown fun? ;)*

"Iterable" tends to imply a particular API contract, so I'll avoid that term here.  A document represents a series of top-level values, and the implicit (default) type of a value is `any`.  If the desired type is `$any` (which is what I'm inferring from your use of `ionValue`), that would be expressed explicitly; for example:

```
type::{
  type: document,
  element: $any,
}
```

"IDL" -- I'll assume you're referring to ISL, (Ion Schema Language).

I agree with the (a)-(d) use cases you've outlined.  We could imagine an Ion Schema implementation that provides a single `validate()` operation to cover over a series of top-level values, and returns a list of validation misses;  however, I think we'd find that contract tedious (or at least inconvenient) to call and potentially less efficient for scenario (a).

The specification avoids wading into API considerations like these, but perhaps we should consider adding a bullet to the "Implementation Considerations" section.

**Comment by pbcornell** [comment]
#62 provides support for the 'document' type via the existing `Type.validate(IonValue)` API (as a document, namely an IonDatagram, *is* an IonValue).

Use cases that require an iterative approach to validating documents (i.e., large documents, or streams of top-level values) has been split off into #61.
