### ISSUE TITLE
Schema resolution fails when multiple of its imports reference the same schema

### ISSUE THREAD

**Issue by saiemani** [amzn/ion-schema-kotlin#115]
Here is my scenario

```
schema-1 imports schema-2, schema-3
schema-2 imports schema-4
schema-3 imports schema-4
```

When attempting to resolve `schema-1`, it fails with `duplicate type name/alias encountered`

```
software.amazon.ionschema.IonSchemaException: Unable to resolve schema id 'repo/Schema-1.isl' ([software.amazon.ionschema.InvalidSchemaException: Duplicate type name/alias encountered:  'Schema4'])
	at software.amazon.ionschema.internal.IonSchemaSystemImpl.loadSchema(IonSchemaSystemImpl.kt:42)
```

I have added the test, I used to reproduce the issue

[ion-schema-test.tar.gz](https://github.com/amzn/ion-schema-kotlin/files/3204273/ion-schema-test.tar.gz)

**Comment by pbcornell** [comment]
Thanks for submitting this, as well as providing a set of example schemas.  This failure is occurring because Schema1's import of Schema3 isn't honoring the "Schema5" alias for Schema4, so Schema1 attempts to import Schema4 twice.  This is a bug.
