### ISSUE TITLE
Regex constraints don't accept multiple ranges in a character class

### ISSUE THREAD

**Issue by mtcalvin** [amzn/ion-schema-kotlin#125]
```
com.amazon.ionschema.InvalidSchemaException: unexpected character '0' in regex '^[A-Z0-9]{10}' at offset 5
	at com.amazon.ionschema.internal.constraint.Regex.error(Regex.kt:205) ~[Maven-com-amazon-ion_ion-schema-kotlin-1.x.jar:?]
	at com.amazon.ionschema.internal.constraint.Regex.parseCharacterClass(Regex.kt:143) ~[Maven-com-amazon-ion_ion-schema-kotlin-1.x.jar:?]
	at com.amazon.ionschema.internal.constraint.Regex.toPattern(Regex.kt:88) ~[Maven-com-amazon-ion_ion-schema-kotlin-1.x.jar:?]
	at com.amazon.ionschema.internal.constraint.Regex.<init>(Regex.kt:58) ~[Maven-com-amazon-ion_ion-schema-kotlin-1.x.jar:?]
```

According to the [Ion Schema Specification](https://amzn.github.io/ion-schema/docs/spec.html#regex), regex constraints conform to [ECMA-262](https://www.ecma-international.org/ecma-262/5.1/#sec-7.8.5) -- it specifically links to the regular expression literal grammar.

The semantics of that literal is defined to be the same as the RegExp constructor, which accepts a [Pattern](https://www.ecma-international.org/ecma-262/5.1/#sec-15.10.1), which permits multiple ranges in one character class.  However, I found [this test case](https://github.com/amzn/ion-schema-kotlin/blob/master/data/test/constraints/regex/invalid.isl#L20) in IonSchema which suggests IonSchema consider this not to be valid.

I'm curious about the reasoning here -- multiple ranges in one character class is a common use case in regexes (e.g. `[a-zA-Z0-9]`).

**Comment by pbcornell** [comment]
The reasoning was for implementation simplicity for the time being, and perhaps that was a poor decision on my part.  I agree that support for multiple ranges should be added.

Apologies for the inconvenience.  In the meantime, one_of (or any_of) enables the use case you describe:
```
one_of: [
  { regex: "a-z" },
  { regex: "A-Z" },
  { regex: "0-9" },
]
```

**Comment by mtcalvin** [comment]
The case I gave above is slightly simplified from the actual problem we encountered with a regex like `^[a-zA-Z0-9]{10}$` -- I'm not sure the `one_of` workaround is usable in that case, but I think this regex is rewritable as `^([a-z]|[A-Z]|[0-9])+$` (although I haven't tried it).

Thanks for the context.

**Comment by pbcornell** [comment]
Agreed, your approach to rewriting the regex is cleaner and all-around better.  :)

**Comment by saiemani** [comment]
I upgraded the IonSchema in my project from 0.7 to 1.x and the regex that I have defined before are having the same issue described above.

is 1.x upgrade not backward compatible?
