### ISSUE TITLE
Javadoc link in README.md is broken

### ISSUE THREAD

**Issue by ivoanjo** [amzn/ion-schema-kotlin#130]
The link points to <http://www.javadoc.io/doc/com.amazon.ion/ion-schema-kotlin> which just says

>  No JavaDoc is released for artifact com.amazon.ion:ion-schema-kotlin:1.0.0. Please try other versions. [...]

Only two versions are listed on that site: 0.8.0 and 1.0.0 and neither has javadoc available.

**Comment by pbcornell** [comment]
Thank you for pointing this out, Ivo.  The javadoc.jar is [available for download](https://search.maven.org/artifact/com.amazon.ion/ion-schema-kotlin/1.0.0/jar) at maven.apache.org, but is clearly not available at javadoc.io.

I suspect this is related to Kotlin's dokka tool; will take a closer look....

**Comment by pbcornell** [comment]
Looks like there are two issues:
* javadoc.io doesn't recognize dokka's "html" outputFormat
* Kotlin's dokka tool fails on JDK 10 or higher when the "javadoc" outputFormat is specified ([dokka/294](https://github.com/Kotlin/dokka/issues/294))

**Comment by pbcornell** [comment]
The link Javadoc link in README.md (http://www.javadoc.io/doc/com.amazon.ion/ion-schema-kotlin) now points to generated javadoc content for a new release, v1.0.1.

Thanks again for identifying this issue, Ivo.  Closing.
