### ISSUE TITLE
[Guidance Needed] How to validate Ion values with an Ion schema that doesn't contain a type name?

### ISSUE THREAD

**Issue by flyingImer** [amzn/ion-schema-kotlin#138]
For example, given an Ion schema `type::{type: bool}`, what type name I should provide when calling `ionSchema.getType("<type_name>")`? 

I see a trimmed schema string (`type::{type:bool}` for the example) is used for the type name in this case, can I rely on it? 

or should I use `ionSchema.getTypes()` instead?

**Comment by pbcornell** [comment]
Relying on a "trimmed schema string" such as `type::{type:bool}` to lookup a type would seem to be a brittle option that should not be relied upon.  I'd recommend giving each top-level type a name and using `getType(name)` to retrieve it.  Is there a reason you want to avoid specifying a name?  If so, I'd like to understand that usage better.

Actually, I'll go a step or two further:  if retrieving a type via `"type::{type:bool}"` works, it sounds like a mis-feature that should probably be removed; additionally, all top-level type definitions within a struct should be required to have a name.

Not sure whether this will be of help to you, but it is perhaps worth noting that the [Core Types and Ion Types](https://amzn.github.io/ion-schema/docs/spec.html#type-system) are built-in and available by simple name.  As such, the specific example you've provided requires no ISL, and one could simply call `schema.getType("bool")`.

**Comment by flyingImer** [comment]
> Relying on a "trimmed schema string" such as `type::{type:bool}` to lookup a type would seem to be a brittle option that should not be relied upon. I'd recommend giving each top-level type a name and using `getType(name)` to retrieve it. Is there a reason you want to avoid specifying a name? If so, I'd like to understand that usage better.

Nuh, I'm building a utility method to validate an Ion value given an Ion schema. So I'm not the owner/author of the Ion schema. However, I found one of the schemas is defined as mentioned above, which breaks my understanding.

> Actually, I'll go a step or two further: if retrieving a type via `"type::{type:bool}"` works, it sounds like a mis-feature that should probably be removed; additionally, all top-level type definitions within a struct should be required to have a name.

Not quite sure I followed your point of `additionally, all top-level type definitions within a struct should be required to have a name.` Could you elaborate a bit? 

> Not sure whether this will be of help to you, but it is perhaps worth noting that the [Core Types and Ion Types](https://amzn.github.io/ion-schema/docs/spec.html#type-system) are built-in and available by simple name. As such, the specific example you've provided requires no ISL, and one could simply call `schema.getType("bool")`.

Wasn't aware of this piece. Thanks for the pointers!

**Comment by pbcornell** [comment]
> additionally, all top-level type definitions within a struct should be required to have a name

Yep, that's not clear at all.  :)  Should be "all top-level type definitions within a *schema*," or simply "all top-level type definitions should be required to have a name."  Does that clear it up?

**Comment by flyingImer** [comment]
Hmmm, I guess the gap is around the definition of `top-level type definition`.

Given a random schema example below, correct me if I'm wrong, I *think* `top-level type definition` is referring to `Details` (as it depends on `Parameters`) 
```
type::{
  name: Parameters,
  type: struct,
  fields: {
      path: { type: string, occurs: optional },
      arguments: { type: string, occurs: optional }
  },
}

type::{
  name: Details,
  type: struct,
  fields: {
      name: { type: string, occurs: optional },
      dependency: { type: string, occurs: required },
      parameters: { type: Parameters, occurs: required },
  },
}
```
My understanding is validation can either go against `Details` or `Parameters`. 

With that said, I feel a type name is required wherever validation goes, from a validation perspective. 

But I could be wrong on my assumptions. LMK

**Comment by pbcornell** [comment]
Ah, I see, we're working with different definitions of "top-level."  Your definition is based on the logical hierarchy of type definitions (in your example, `Details` is the "root" or "top-level" type), and my definition of "top-level" refers to the physical layout of types within a schema definition (`Details` and `Parameters` are "top-level", as they are not nested inside other type definitions).  Without a name, a top-level type definition doesn't provide any value:  you shouldn't be able to retrieve one in order to validate against it, *and* other type definitions can't refer to it.

Let's say you never needed to validate against `Parameters`, *and* it is not useful as a reusable type definition.  We might still write the ISL as your example shows; but it could also be rewritten as follows:

```
type::{
  name: Details,
  type: struct,
  fields: {
      name: { type: string, occurs: optional },
      dependency: { type: string, occurs: required },
      parameters: {
        type: type::{         // an inline type definition, not reusable
            type: struct,     // and can't be referred to, so naming it is irrelevant
            fields: {
                path: { type: string, occurs: optional },
                arguments: { type: string, occurs: optional }
            },
        },
        occurs: required,
      },
  },
}
```

More generally, my intent is that all 5 types in the following schema are "top-level" and must have a name, independent of whether or how they are related to one another:
```
schema_header::{}
type::{ ... }    // top-level type definition
type::{ ... }    // top-level type definition
type::{ ... }    // top-level type definition
type::{ ... }    // top-level type definition
type::{ ... }    // top-level type definition
schema_footer::{}
```

**Comment by flyingImer** [comment]
> Ah, I see, we're working with different definitions of "top-level." Your definition is based on the logical hierarchy of type definitions (in your example, `Details` is the "root" or "top-level" type), and my definition of "top-level" refers to the physical layout of types within a schema definition (`Details` and `Parameters` are "top-level", as they are not nested inside other type definitions). Without a name, a top-level type definition doesn't provide any value: you shouldn't be able to retrieve one in order to validate against it, _and_ other type definitions can't refer to it.

Yep, totally agree.

> Let's say you never needed to validate against `Parameters`, _and_ it is not useful as a reusable type definition. We might still write the ISL as your example shows; but it could also be rewritten as follows:
> 
> ```
> type::{
>   name: Details,
>   type: struct,
>   fields: {
>       name: { type: string, occurs: optional },
>       dependency: { type: string, occurs: required },
>       parameters: {
>         type: type::{         // an inline type definition, not reusable
>             type: struct,     // and can't be referred to, so naming it is irrelevant
>             fields: {
>                 path: { type: string, occurs: optional },
>                 arguments: { type: string, occurs: optional }
>             },
>         },
>         occurs: required,
>       },
>   },
> }
> ```
> 
> More generally, my intent is that all 5 types in the following schema are "top-level" and must have a name, independent of whether or how they are related to one another:
> 
> ```
> schema_header::{}
> type::{ ... }    // top-level type definition
> type::{ ... }    // top-level type definition
> type::{ ... }    // top-level type definition
> type::{ ... }    // top-level type definition
> type::{ ... }    // top-level type definition
> schema_footer::{}
> ```

Thanks for the thorough explanation and guidance! It would be great if any guidance page can capture these best practices (LMK if there is one already)

**Comment by pbcornell** [comment]
Ok, I've opened an issue to enforce the naming rules described above.  We don't have a guidance page or much in the way of "getting started" at this time--we need to improve on that front, and I've opened a second issue for that.

Closing, as the original questions raised have been addressed (and follow-up issues have been created).
